ALTER TABLE step ADD sync_at TIMESTAMP NULL;
ALTER TABLE path_step ADD sync_at TIMESTAMP NULL;
ALTER TABLE intent ADD sync_at TIMESTAMP NULL;
ALTER TABLE trek ADD sync_at TIMESTAMP NULL;
ALTER TABLE question ADD sync_at TIMESTAMP NULL;
ALTER TABLE answer ADD sync_at TIMESTAMP NULL;
ALTER TABLE tag ADD sync_at TIMESTAMP NULL;
ALTER TABLE step_tag ADD sync_at TIMESTAMP NULL;
